// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrD-TotWegkqD0GKzKBOv-Yr1lDJKof8E',
    appId: '1:1089601888148:web:1fb470c4c1b786392df981',
    messagingSenderId: '1089601888148',
    projectId: 'poultry-automation-93ae1',
    authDomain: 'poultry-automation-93ae1.firebaseapp.com',
    databaseURL: 'https://poultry-automation-93ae1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poultry-automation-93ae1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXkVloZYl41KoGBrCHhDIAN4zXQQ7-hgg',
    appId: '1:1089601888148:ios:e03a02cfa5af07d62df981',
    messagingSenderId: '1089601888148',
    projectId: 'poultry-automation-93ae1',
    databaseURL: 'https://poultry-automation-93ae1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poultry-automation-93ae1.firebasestorage.app',
    iosBundleId: 'com.example.poultryAutomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXkVloZYl41KoGBrCHhDIAN4zXQQ7-hgg',
    appId: '1:1089601888148:ios:e03a02cfa5af07d62df981',
    messagingSenderId: '1089601888148',
    projectId: 'poultry-automation-93ae1',
    databaseURL: 'https://poultry-automation-93ae1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poultry-automation-93ae1.firebasestorage.app',
    iosBundleId: 'com.example.poultryAutomation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrD-TotWegkqD0GKzKBOv-Yr1lDJKof8E',
    appId: '1:1089601888148:web:72de4cd9a50377732df981',
    messagingSenderId: '1089601888148',
    projectId: 'poultry-automation-93ae1',
    authDomain: 'poultry-automation-93ae1.firebaseapp.com',
    databaseURL: 'https://poultry-automation-93ae1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poultry-automation-93ae1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgIEQ8ln76HFnEVy8hdViQXHRRJnu0lQI',
    appId: '1:1089601888148:android:e1f1fbd55dc09f712df981',
    messagingSenderId: '1089601888148',
    projectId: 'poultry-automation-93ae1',
    databaseURL: 'https://poultry-automation-93ae1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'poultry-automation-93ae1.firebasestorage.app',
  );

}